<?php

namespace OrnithoPinniBundle\Repository\ECHOUAGE;

/**
 * BiometrieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BiometrieRepository extends \Doctrine\ORM\EntityRepository
{
}
