<?php

namespace OrnithoPinniBundle\Repository\ECHOUAGE;

/**
 * ProtocoleOpportunisteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProtocoleOpportunisteRepository extends \Doctrine\ORM\EntityRepository
{
}
