<?php

namespace OrnithoPinniBundle\Repository\ECHOUAGE;

/**
 * ProtocoleEnTourneeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProtocoleEnTourneeRepository extends \Doctrine\ORM\EntityRepository
{
}
