<?php

namespace OrnithoPinniBundle\Repository\General;

/**
 * ManipRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ManipRepository extends \Doctrine\ORM\EntityRepository
{
}
