<?php

namespace OrnithoPinniBundle\Repository\General;

/**
 * ManipSurveillanceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ManipSurveillanceRepository extends \Doctrine\ORM\EntityRepository
{
}
