<?php

namespace OrnithoPinniBundle\Repository\General;

/**
 * Position_GPSRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Position_GPSRepository extends \Doctrine\ORM\EntityRepository
{
}
