<?php

namespace OrnithoPinniBundle\Repository\General;

/**
 * ProtocoleSurveillanceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProtocoleSurveillanceRepository extends \Doctrine\ORM\EntityRepository
{
}
