<?php

namespace OrnithoPinniBundle\Repository\General;

/**
 * ProtocoleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProtocoleRepository extends \Doctrine\ORM\EntityRepository
{
  public function findFromCMTG($cmtg_id){
    $sql = "
    SELECT m.id
      FROM general_manip AS m,
           general_protocole AS p
     WHERE p.manip_id = m.id AND p.cmtg_indiff_protocole_id = ".$cmtg_id.";"
    ;
    $stmt = $this->getEntityManager()->getConnection()->prepare($sql);
    $stmt->execute();
    return $stmt->fetchAll();
  }
}
