<?php

namespace OrnithoPinniBundle\Repository\PC;

/**
 * DonneesTerrierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DonneesTerrierRepository extends \Doctrine\ORM\EntityRepository
{
}
