<?php

namespace OrnithoPinniBundle\Repository\PC;

/**
 * PiquetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PiquetRepository extends \Doctrine\ORM\EntityRepository
{
}
