<?php

namespace OrnithoPinniBundle\Repository\PC;

/**
 * PointComptageTransectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PointComptageTransectRepository extends \Doctrine\ORM\EntityRepository
{
}
