<?php

namespace OrnithoPinniBundle\Repository\PC;

/**
 * PointComptagePermanentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PointComptagePermanentRepository extends \Doctrine\ORM\EntityRepository
{
}
