<?php

namespace OrnithoPinniBundle\Repository\PC;

/**
 * ProtocolePermanentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProtocolePermanentRepository extends \Doctrine\ORM\EntityRepository
{
}
