<?php

namespace OrnithoPinniBundle\Repository\PC;

/**
 * ProtocoleTransectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProtocoleTransectRepository extends \Doctrine\ORM\EntityRepository
{
}
