<?php

namespace OrnithoPinniBundle\Repository\PC;

/**
 * VegetationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VegetationRepository extends \Doctrine\ORM\EntityRepository
{
}
