<?php

namespace CommersonBundle\Repository;

/**
 * BiopsieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BiopsieRepository extends \Doctrine\ORM\EntityRepository
{
}
