<?php

namespace CommersonBundle\Repository;

/**
 * ObservationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ObservationRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAllCodes($sortie)
    {
        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb->select('obs.codeObservation')
           ->from('CommersonBundle:Observation','obs')
           ->where('obs.sortie = ?1')
           ->orderBy('obs.codeObservation', 'DESC')
           ->setParameter(1, $sortie);
        return $qb->getQuery()->getResult();
    }

    public function selectAll()
    {
        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb->select('o')
           ->from('CommersonBundle:Observation','o')
        ;
        return $qb->getQuery()->getResult();
    }
}
