<?php

namespace OrnithoPinniBundle\Repository\CMTG_OISEAUX_MARINS;

/**
 * ColonieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ColonieRepository extends \Doctrine\ORM\EntityRepository
{
}
