<?php

namespace OrnithoPinniBundle\Repository\CMTG_GOEL;

/**
 * PassageSurColonieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PassageSurColonieRepository extends \Doctrine\ORM\EntityRepository
{
}
