<?php

namespace OrnithoPinniBundle\Repository\TRSC_EPI;

/**
 * SaisiePointTransectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SaisiePointTransectRepository extends \Doctrine\ORM\EntityRepository
{
}
