<?php

namespace OrnithoPinniBundle\Repository\DEMOS;

/**
 * InformationPremierPassageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InformationPremierPassageRepository extends \Doctrine\ORM\EntityRepository
{
}
