<?php

namespace OrnithoPinniBundle\Repository\DEMOS;

/**
 * PassageSurTerrierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PassageSurTerrierRepository extends \Doctrine\ORM\EntityRepository
{
    public function findFromSeason($specy){
      //Si pas de passage sue le terrier --> renvoie []
      $sql = "
      SELECT demos_terrier.numero_piquet,
             demos_terrier.id,
             demos_terrier.code_piquet,
             e.nom_courant,
             demos_terrier.date_dernier_passage,
             demos_protocole.saison
        FROM general_espece AS e,
             demos_terrier LEFT JOIN demos_passage_sur_terrier ON demos_terrier.id = demos_passage_sur_terrier.terrier_id
                           LEFT JOIN demos_protocole ON demos_passage_sur_terrier.protocole_id = demos_protocole.id
       WHERE e.id = demos_terrier.espece_id
         AND e.nom_courant LIKE '".$specy."'
         ;"
      ;
      $stmt = $this->getEntityManager()->getConnection()->prepare($sql);
      $stmt->execute();
      return $stmt->fetchAll();
    }
}
