<?php

namespace OrnithoPinniBundle\Repository\DEMOS;

/**
 * TerrierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TerrierRepository extends \Doctrine\ORM\EntityRepository
{
}
