<?php

namespace FrequentationBundle\Repository;

/**
 * ManipeurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ManipeurRepository extends \Doctrine\ORM\EntityRepository
{
}
