<?php

namespace FrequentationBundle\Repository;

/**
 * ManipeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ManipeRepository extends \Doctrine\ORM\EntityRepository
{
}
