<?php

namespace FrequentationBundle\Repository;

/**
 * ProgrammeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProgrammeRepository extends \Doctrine\ORM\EntityRepository
{
    //   public function programmeAll(){

    //             $qb=$this->createQueryBuilder('p');

    //             $qb

    //                 ->leftJoin('p.autorisations','a')
    //                 ->addSelect('a')
    //                 ->leftJoin('a.zoneSite','z')
    //                 ->addSelect('z')
    //                 ->leftJoin('p.users','u')
    //                 ->addSelect('u')
    //                 ->leftJoin('u.mouvements','mv')
    //                 ->addSelect('mv')
    //                 ->leftJoin('mv.manipe','mp')
    //                 ->addSelect('mp')


    //             ;

    //             return $qb->getQuery()->getResult();

    //     }
}
