<?php

namespace HFIBundle\Repository;

/**
 * SystematiqueInvertebreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SystematiqueInvertebreRepository extends \Doctrine\ORM\EntityRepository
{
}
