<?php

namespace HFIBundle\Repository;

/**
 * DescriptionInvertebreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DescriptionInvertebreRepository extends \Doctrine\ORM\EntityRepository
{
  public function checkInvertebre($foreignKey)
  {
    $sql = "SELECT CAST(CASE WHEN COUNT(*) > 0 THEN true ELSE false END AS bool)
      FROM description_invertebre WHERE observation_id=" . $foreignKey;
    $stmt = $this->getEntityManager()->getConnection()->prepare($sql);
    $stmt->execute();
    return $stmt->fetch()["bool"];
  }
}
