<?php

namespace HFIBundle\Repository;

/**
 * DescriptionVertebreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DescriptionVertebreRepository extends \Doctrine\ORM\EntityRepository
{
}
