<?php

namespace HFIBundle\Repository;

/**
 * EradicationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EradicationRepository extends \Doctrine\ORM\EntityRepository
{
}
