<?php

namespace HFIBundle\Repository;

/**
 * FicheTerrainRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FicheTerrainRepository extends \Doctrine\ORM\EntityRepository
{
  public function getFicheTerrain($id)
  {
    $ficheTerrain = $this->createQueryBuilder('q')
      ->select('q.typeMilieu, q.nStatutReleveVegetation, q.nStatutFiche,
        q.nStatutFiche, q.milieuAutre, q.topographie, q.topoAutre, q.pente,
        q.orientation, q.conditionExposition, q.erosion, q.erosionAutre,
        q.recBlocs, q.recCailloux, q.recSols, q.recGraviers, q.recStrateBryoLichenique,
        q.recStrateHerbacee, q.hauteurVegetation, q.habitat, q.commentaireHabitat,
        q.substrat, q.epaisseurSubstrat, q.microRelief, q.penteMicroTopo, q.humidite,
        q.particulariteGeologique, q.categorieMeteo, q.commentaire, q.nomIdentiteSite')
      ->where('q.id = :id')
      ->setParameter('id', $id)
      ->getQuery();

    return($ficheTerrain->getResult());
  }
}
