<?php

namespace HFIBundle\Repository;

/**
 * MethodologieInvertebreBundleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MethodologieInvertebreRepository extends \Doctrine\ORM\EntityRepository
{
}
