<?php

namespace HFIBundle\Repository;

/**
 * SuiviRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SuiviRepository extends \Doctrine\ORM\EntityRepository
{
  public function getSuivi($id)
  {
    $suivi = $this->createQueryBuilder('q')
      ->select('q.mort, q.nonTrouve')
      ->where('q.id = :id')
      ->setParameter('id', $id)
      ->getQuery();
    return !empty($suivi->getResult()) ? $suivi->getResult()[0] : null;
  }
}
