<?php

namespace HFIBundle\Repository;

/**
 * SystematiqueFloreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SystematiqueFloreRepository extends \Doctrine\ORM\EntityRepository
{
}
