<?php

namespace HFIBundle\Repository;

/**
 * SystematiqueVertebreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SystematiqueVertebreRepository extends \Doctrine\ORM\EntityRepository
{
}
