<?php

namespace HFIBundle\Repository;

/**
 * ToponymeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ToponymeRepository extends \Doctrine\ORM\EntityRepository
{
}
