<?php

namespace HFIBundle\Repository;

/**
 * ZoneBioGeographiqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ZoneBioGeographiqueRepository extends \Doctrine\ORM\EntityRepository
{
}
