<?php

namespace OrnithoPinniBundle\Repository\CMTG_INDIFF;

/**
 * ComptagePrecisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ComptagePrecisRepository extends \Doctrine\ORM\EntityRepository
{
}
