<?php

namespace OrnithoPinniBundle\Repository\CMTG_INDIFF;

/**
 * ProtocoleClasseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProtocoleClasseRepository extends \Doctrine\ORM\EntityRepository
{
}
