<?php

namespace OrnithoPinniBundle\Repository\Bague;

/**
 * ControleRepriseBagueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ControleRepriseBagueRepository extends \Doctrine\ORM\EntityRepository
{
}
