<?php

namespace OrnithoPinniBundle\Repository\SREP;

/**
 * SaisieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SaisieRepository extends \Doctrine\ORM\EntityRepository
{
}
