<?php

namespace OrnithoPinniBundle\Repository\SAGIR;

/**
 * DecouverteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DecouverteRepository extends \Doctrine\ORM\EntityRepository
{
}
